---
- hosts: localhost
  pre_tasks:
    - name: Install unzip
      package:
        name: unzip
        state: present
  roles:
    - role: diodonfrost.terraform

- hosts: localhost
  roles:
    - role: codedeploy