---
# defaults file for code-deploy

# REQURED for the deploy_code role. This is not required in order to run the create_aws_ec2_host role
name_of_private_key_file: "id_rsa" # REQUIRED - CHANGE THIS - Keyfile for SSH capability. WIP

code_repo_destination_directory: "/usr/share/." # REQUIRED - CHANGE THIS -  to whatever destination directory you'd like
code_repo_name: "simple-nodejs-server" # REQUIRED - CHANGE THIS to the git repo or name of directory where you'd like the code to sit
code_service_description: "A simple nodejs server"
code_service_name: "simple_nodejs_server"
code_service_file_name: "{{ code_service_name }}.service"

resolve_dependencies: true # Will trigger the ansible tasks to execute a script file to resolve dependencies before the app initialization
application_dependencies_file_name: "example_dependency_script.sh" # REQUIRED - CHANGE THIS - The .sh file that contians commands to resolve your app dependencies
application_initialization_script_name: "example_initialization_script.sh" # REQUIRED - CHANGE THIS - This script file should execute your app code
app_init_extra_vars: ""

use_git: true
git_repo_https_url: "https://github.com/alinebastos/simple-nodejs-server.git" # REQUIRED - CHANGE THIS - to your HTTPS url for your git
